name: PlayerWarps
authors: [Revivalo]
description: Warps created by players for players
version: ${project.version}

main: dev.revivalo.playerwarps.PlayerWarpsPlugin
api-version: 1.13
softdepend:
  - Vault
  - Multiverse-Core
  - Multiworld
  - DiscordSRV
  - ChatControlRed
  - ChatControl
  - Essentials
  - dynmap
  - BlueMap
  - BentoBox
  - SuperiorSkyblock2
  - WorldGuard
  - GriefPrevention
  - Residence
  - Territory # Get the plugin here:

commands:
  pwarp:
    description: Main command for PlayerWarps plugin
    usage: /<command>
    aliases: [pw, playerwarps]

permissions:
  playerwarps.use:
    description: Allows you to teleport to public warps
    default: true
  playerwarps.create:
    description: Allows you to create a warp
    default: true
  playerwarps.settings:
    description: Allows you to setup the warp
    default: true
  playerwarps.delay.1:
    description: Sets teleport delay to 1 second
    default: false
  playerwarps.delay.2:
    description: Sets teleport delay to 2 seconds
    default: false
  playerwarps.delay.3:
    description: Sets teleport delay to 3 seconds
    default: false
  playerwarps.delay.4:
    description: Sets teleport delay to 4 seconds
    default: false
  playerwarps.delay.5:
    description: Sets teleport delay to 5 seconds
    default: false